### ISSUE TITLE
HUGO Build page failed on Netlify

### ISSUE THREAD

**Issue by SUNLOVEERIN** [kaapiandcode/hugo-goa#102]
Hi, everyone. Previos web has been built successfully, i didn't changes anything, but failed this time.  I was wondering how to fix this problem?
Thanks so much

10:13:55 PM: Build ready to start
10:13:57 PM: build-image version: 8925038cf853b22d6397cdcb9904ac88b66bb383 (focal)
10:13:57 PM: build-image tag: v4.5.0
10:13:57 PM: buildbot version: 1166b873df3086892bcef41356ad6efa7b9e401d
10:13:57 PM: Fetching cached dependencies
10:13:57 PM: Failed to fetch cache, continuing with build
10:13:57 PM: Starting to prepare the repo for build
10:13:58 PM: No cached dependencies found. Cloning fresh repo
10:13:58 PM: git clone https://github.com/SUNLOVEERIN/academic-page
10:14:00 PM: Preparing Git Reference refs/heads/main
10:14:02 PM: Parsing package.json dependencies
10:14:02 PM: Different build command detected, going to use the one specified in the Netlify configuration file: 'hugo --gc --minify -b $URL' versus 'hugo --gc --minify' in the Netlify UI
10:14:03 PM: Starting build script
10:14:03 PM: Installing dependencies
10:14:03 PM: Python version set to 2.7
10:14:04 PM: v16.13.0 is already installed.
10:14:04 PM: Now using node v16.13.0 (npm v8.1.0)
10:14:04 PM: Started restoring cached build plugins
10:14:04 PM: Finished restoring cached build plugins
10:14:05 PM: Attempting ruby version 2.7.2, read from environment
10:14:06 PM: Using ruby version 2.7.2
10:14:07 PM: Using PHP version 8.0
10:14:07 PM: Installing Hugo 0.87.0
10:14:08 PM: hugo v0.87.0-B0C541E4+extended linux/amd64 BuildDate=2021-08-03T10:57:28Z VendorInfo=gohugoio
10:14:08 PM: Started restoring cached go cache
10:14:08 PM: Finished restoring cached go cache
10:14:08 PM: go version go1.16.5 linux/amd64
10:14:08 PM: go version go1.16.5 linux/amd64
10:14:08 PM: Installing missing commands
10:14:08 PM: Verify run directory
10:14:10 PM: ​
10:14:10 PM: ────────────────────────────────────────────────────────────────
10:14:10 PM:   Netlify Build                                                 
10:14:10 PM: ────────────────────────────────────────────────────────────────
10:14:10 PM: ​
10:14:10 PM: ❯ Version
10:14:10 PM:   @netlify/build 18.24.0
10:14:10 PM: ​
10:14:10 PM: ❯ Flags
10:14:10 PM:   baseRelDir: true
10:14:10 PM:   buildId: 6197a31366e7a800bc770162
10:14:10 PM:   deployId: 6197a31366e7a800bc770164
10:14:10 PM: ​
10:14:10 PM: ❯ Current directory
10:14:10 PM:   /opt/build/repo
10:14:10 PM: ​
10:14:10 PM: ❯ Config file
10:14:10 PM:   /opt/build/repo/netlify.toml
10:14:10 PM: ​
10:14:10 PM: ❯ Context
10:14:10 PM:   production
10:14:10 PM: ​
10:14:10 PM: ❯ Installing plugins
10:14:10 PM:    - netlify-plugin-hugo-cache-resources@0.2.1
10:14:12 PM: ​
10:14:12 PM: ❯ Loading plugins
10:14:12 PM:    - netlify-plugin-hugo-cache-resources@0.2.1 from netlify.toml
10:14:12 PM: ​
10:14:12 PM: ────────────────────────────────────────────────────────────────
10:14:12 PM:   1. netlify-plugin-hugo-cache-resources (onPreBuild event)     
10:14:12 PM: ────────────────────────────────────────────────────────────────
10:14:12 PM: ​
10:14:12 PM: Checking if resources exist at "resources"
10:14:12 PM: No cache found for resources folder
10:14:12 PM: ​
10:14:12 PM: (netlify-plugin-hugo-cache-resources onPreBuild completed in 216ms)
10:14:12 PM: ​
10:14:12 PM: ────────────────────────────────────────────────────────────────
10:14:12 PM:   2. build.command from netlify.toml                            
10:14:12 PM: ────────────────────────────────────────────────────────────────
10:14:12 PM: ​
10:14:12 PM: $ hugo --gc --minify -b $URL
10:14:12 PM: Start building sites …
10:14:12 PM: hugo v0.87.0-B0C541E4+extended linux/amd64 BuildDate=2021-08-03T10:57:28Z VendorInfo=gohugoio
10:14:16 PM: Error: Error building site: failed to render pages: render of "home" failed: execute of template failed: template: index.html:21:5: executing "main" at <partial "widget_page.html" .>: error calling partial: execute of template failed: template: partials/widget_page.html:146:9: executing "partials/widget_page.html" at <partial $widget_path $widget_args>: error calling partial: "/opt/build/repo/themes/github.com/wowchemy/wowchemy-hugo-modules/wowchemy/v5/layouts/partials/widgets/accomplishments.html:35:18": execute of template failed: template: partials/widgets/accomplishments.html:35:18: executing "partials/widgets/accomplishments.html" at <time .date_start>: error calling time: unable to parse date: 2021-10-1
10:14:16 PM: Total in 4013 ms
10:14:16 PM: ​
10:14:16 PM: ────────────────────────────────────────────────────────────────
10:14:16 PM:   "build.command" failed                                        
10:14:16 PM: ────────────────────────────────────────────────────────────────
10:14:16 PM: ​
10:14:16 PM:   Error message
10:14:16 PM:   Command failed with exit code 255: hugo --gc --minify -b $URL
10:14:16 PM: ​
10:14:16 PM:   Error location
10:14:16 PM:   In build.command from netlify.toml:
10:14:16 PM:   hugo --gc --minify -b $URL
10:14:16 PM: ​
10:14:16 PM:   Resolved config
10:14:16 PM:   build:
10:14:16 PM:     command: hugo --gc --minify -b $URL
10:14:16 PM:     commandOrigin: config
10:14:16 PM:     environment:
10:14:16 PM:       - HUGO_VERSION
10:14:16 PM:       - HUGO_ENABLEGITINFO
10:14:16 PM:       - HUGO_ENV
10:14:16 PM:     publish: /opt/build/repo/public
10:14:16 PM:     publishOrigin: config
10:14:16 PM:   plugins:
10:14:16 PM:     - inputs:
10:14:16 PM:         debug: true
10:14:16 PM:       origin: config
10:14:16 PM:       package: netlify-plugin-hugo-cache-resources
10:14:17 PM: Caching artifacts
10:14:17 PM: Started saving build plugins
10:14:17 PM: Finished saving build plugins
10:14:17 PM: Started saving pip cache
10:14:17 PM: Finished saving pip cache
10:14:17 PM: Started saving emacs cask dependencies
10:14:17 PM: Finished saving emacs cask dependencies
10:14:17 PM: Started saving maven dependencies
10:14:17 PM: Finished saving maven dependencies
10:14:17 PM: Started saving boot dependencies
10:14:17 PM: Finished saving boot dependencies
10:14:17 PM: Started saving rust rustup cache
10:14:17 PM: Finished saving rust rustup cache
10:14:17 PM: Started saving go dependencies
10:14:17 PM: Finished saving go dependencies
10:14:19 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
10:14:19 PM: Creating deploy upload records
10:14:19 PM: Failing build: Failed to build site
10:14:19 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2
10:14:19 PM: Finished processing build request in 21.90925132s

**Comment by kaapiandcode** [comment]
not sure where this is coming from but perhaps the error is `https://github.com/mixchat-io/mixchat/pull/2` @SUNLOVEERIN
