### ISSUE TITLE
YouTube channel link doesn't work for all channels

### ISSUE THREAD

**Issue by jlouder** [kaapiandcode/hugo-goa#87]
Hi,

I'm new to this theme and just getting started. I noticed that the YouTube social link changed in a recent commit (02d747783cdd8fbc82406b949689087bb32233e3) changed the channel link from:

youtube.com/channel/{name}

To:

youtube.com/c/{name}

The second form is a YouTube custom channel URL, which not all channels are eligible for (see YouTube's [eligibility requirements](https://support.google.com/youtube/answer/2657968#eligibility)).

It would be nice if there was a way to have social links for YouTube that work for every channel, but still allow users with a custom channel URL to use that.

If you are willing, I could put together a pull request. I was thinking you could do something like split the `youtube` param in config.toml into two -- one for a channel ID and one for a custom channel name, and users could use one or the other.

Before I put together a pull request, is that an approach you'd want to take? I'm sure there are other ways to solve this, too.

**Comment by shenoybr** [comment]
@jlouder Yes. Feel free to submit a PR and I'll merge it.
