### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by shenwei356** [kaapiandcode/hugo-goa#96]
Using hugo 0.80.0 or newer version in 2019 failed to parse the example site:

    cd themes/hugo-goa/exampleSite/
    hugo server

> Error: Error building site: failed to render pages: render of "home" failed: "/home/shenwei/shenwei/scripts/github/shenwei.me/themes/hugo-goa/exampleSite/themes/hugo-goa/layouts/index.html:3:21": execute of template failed: template: index.html:9:3: executing "index.html" at <partial "main_menu.html" .>: error calling partial: "/home/shenwei/shenwei/scripts/github/shenwei.me/themes/hugo-goa/exampleSite/themes/hugo-goa/layouts/partials/main_menu.html:3:21": execute of template failed: template: partials/main_menu.html:3:21: executing "partials/main_menu.html" at <.Site.Menus.main>: can't evaluate field Site in type navigation.Menu

**Comment by parvez0** [comment]
Hey shenwei created a pull request for this issue here #97

**Comment by shenwei356** [comment]
Good to see it!
