### ISSUE TITLE
How to use academicons

### ISSUE THREAD

**Issue by marcelorpf** [kaapiandcode/hugo-goa#98]
Thanks for the theme! It is really great! Is there a way to use ai icons (academicons) like ORCID and Publons icons?

**Comment by aperov9** [comment]
Hi, is this still relevant? I was able to test adding the ORCID and Publons icon form academicons.

![image](https://user-images.githubusercontent.com/28958978/154606933-0a0b6885-30bb-429a-b015-2b547e8b3766.png)

Do you need anything else? I could theoretically add all icons from academicons.
